#server:
#  port: 8080
#env:
#  model: Standard

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver
#    url: jdbc:mysql://localhost:3306/test
    url: jdbc:h2:mem:testDB;
    username: root
    password: root
    # 开启这个配置就可以通过 web 页面访问了，例如：http://localhost:8080/springboot-h2/h2-console
  h2:
    console:
      enabled: true
      settings:
        # 开启h2 console 跟踪 方便调试  默认 false
        trace: true
        # 允许console 远程访问 默认false
        web-allow-others: true
        # h2 访问路径上下文
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
#      data-locations: classpath:sql/data.sql

mybatis-plus:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl